nameOverride: ""
fullnameOverride: ""
replicaCount: 2
image:
  repository: gcr.io/google-samples/hello-app
  tag: "1.0"
  pullPolicy: IfNotPresent
podAnnotations: {}
service:
  type: ClusterIP
  port: 80
  targetPort: 8080
ingress:
  enabled: true
  className: "nginx"
  annotations:
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
  hosts:
    - host: dummytest.martinn.no
      paths:
        - path: /
          pathType: ImplementationSpecific
  tls:
   - secretName: dummytest-tls
     hosts:
       - dummytest.martinn.no
resources: {}
nodeSelector: {}
tolerations: []
affinity: {}
