kube-prometheus-stack:
  namespaceOverride: monitoring

  alertmanager:
    enabled: false            # Lens doesn’t need alerts

  grafana:
    enabled: false            # Lens provides the UI

  kubeStateMetrics:
    enabled: false            # not needed for CPU/mem metrics
