apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: infisical
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Martinii89/argocd.git
    path: infra/apps/infisical
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: secrets-management
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated: 
      prune: true 
      selfHeal: true   
