infisical-standalone:
  infisical:
    replicaCount: 1
    image:
      repository: infisical/infisical
      tag: "v0.153.1"
      pullPolicy: IfNotPresent
  ingress:
    nginx:
      enabled: false
