apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dummy-app
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Martinii89/argocd.git
    path: charts/dummy-app
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: dummy-app
  syncPolicy:
    automated:
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
