apiVersion: v2
name: cloudnative-pg
description: Umbrella chart that installs the CloudNativePG operator.
type: application
version: 1.0.0
dependencies:
  - name: cloudnative-pg
    version: 0.26.1
    repository: https://cloudnative-pg.github.io/charts
