{{- if .Values.traefik.host }}
apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "dummy-app.fullname" . }}
  labels:
    {{- include "dummy-app.labels" . | nindent 4 }}
spec:
  entryPoints:
    {{- range .Values.traefik.entryPoints }}
    - {{ . }}
    {{- end }}
  routes:
    - match: Host(`{{ .Values.traefik.host }}`)
      kind: Rule
      {{- with .Values.traefik.middlewares }}
      middlewares:
        {{- range . }}
        - name: {{ . }}
        {{- end }}
      {{- end }}
      services:
        - name: {{ include "dummy-app.fullname" . }}
          port: {{ .Values.service.port }}
  {{- with .Values.traefik.tls }}
  tls:
    {{- if .certResolver }}
    certResolver: {{ .certResolver }}
    {{- end }}
    {{- with .secretName }}
    secretName: {{ . }}
    {{- end }}
  {{- end }}
{{- end }}
