ingress-nginx:
  controller:
    # A replica count of minimum 2 ensures high availability for Nginx Ingress main application Pods
    replicaCount: 2
    service:
      type: LoadBalancer

    # Allow snippet annotations (required for advanced routing configurations)
    allowSnippetAnnotations: true

    config:
      use-forwarded-headers: "true"
      compute-full-forwarded-for: "true"
      proxy-real-ip-cidr: "0.0.0.0/0"

    ## Enable the metrics of the NGINX Ingress controller https://kubernetes.github.io/ingress-nginx/user-guide/monitoring/
    metrics:
      enabled: true
      service:
        servicePort: "9090"
    podAnnotations:
      prometheus.io/port: "10254"
      prometheus.io/scrape: "true"
