apiVersion: v2
name: external-secrets
description: Umbrella chart that deploys External Secrets Operator for Kubernetes.
type: application
version: 1.0.0
dependencies:
  - name: external-secrets
    version: 0.20.4
    repository: https://charts.external-secrets.io
