external-secrets:
  # Install CRDs as part of the helm chart
  installCRDs: true
  
  # Enable all cluster-scoped CRDs
  crds:
    createClusterExternalSecret: true
    createClusterSecretStore: true
    createClusterGenerator: true
    createClusterPushSecret: true
    createPushSecret: true
  
  # Resource limits for better resource management
  resources:
    requests:
      cpu: 10m
      memory: 64Mi
    limits:
      cpu: 100m
      memory: 128Mi
  
  # Webhook configuration
  webhook:
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        cpu: 100m
        memory: 64Mi
  
  # Certificate controller configuration
  certController:
    resources:
      requests:
        cpu: 10m
        memory: 32Mi
      limits:
        cpu: 100m
        memory: 64Mi
  
  # Enable ServiceMonitor for Prometheus (if you're using it)
  serviceMonitor:
    enabled: false
