apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: {{ include "fjelltrimmen.fullname" . }}-doppler-store
  labels:
    {{- include "fjelltrimmen.labels" . | nindent 4 }}
spec:
  provider:
    doppler:
      auth:
        secretRef:
          dopplerToken:
            name: {{ .Values.doppler.tokenSecretName }}
            key: {{ .Values.doppler.tokenSecretKey }}
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: {{ include "fjelltrimmen.fullname" . }}-external-secrets
  labels:
    {{- include "fjelltrimmen.labels" . | nindent 4 }}
spec:
  secretStoreRef:
    kind: SecretStore
    name: {{ include "fjelltrimmen.fullname" . }}-doppler-store
  target:
    name: {{ include "fjelltrimmen.fullname" . }}-secrets
  dataFrom:
    - find:
        name:
          regexp: .*
---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: {{ .Values.doppler.tokenSecretName }}
  labels:
    {{- include "fjelltrimmen.labels" . | nindent 4 }}
spec:
  encryptedData:
    {{ .Values.doppler.tokenSecretKey }}: {{ .Values.doppler.encryptedToken | quote }}
  template:
    metadata:
      name: {{ .Values.doppler.tokenSecretName }}