{{- if .Values.ingress.enabled -}}
{{- $crawlerPattern := .Values.crawlerRouting.crawlerPatterns | default "" | replace "\r\n" "" | replace "\n" "" | replace "\r" "" | trim }}
{{- $rewrite := .Values.crawlerRouting.rewrite | default dict -}}
{{- $rewriteEnabled := $rewrite.enabled | default false -}}
{{- $rewriteTarget := $rewrite.target | default "/api/preview/$1" -}}
{{- $customHeaderName := .Values.crawlerRouting.customHeader.name | default "X-Crawler-Request" }}
{{- $customHeaderValue := .Values.crawlerRouting.customHeader.value | default "true" }}
# Main ingress with conditional routing based on User-Agent
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "dummy-app.fullname" . }}
  labels:
    {{- include "dummy-app.labels" . | nindent 4 }}
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- if .Values.crawlerRouting.enabled }}
    {{- if $rewriteEnabled }}
    {{- end }}
    {{- end }}
spec:
  {{- with .Values.ingress.className }}
  ingressClassName: {{ . }}
  {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- range .Values.ingress.tls }}
    - hosts:
        {{- range .hosts }}
        - {{ . | quote }}
        {{- end }}
      secretName: {{ .secretName }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.ingress.hosts }}
    - host: {{ .host | quote }}
      http:
        paths:
          {{- range .paths }}
          - path: {{ .path }}
            {{- with .pathType }}
            pathType: {{ . }}
            {{- end }}
            backend:
              service:
                name: {{ include "dummy-app.fullname" $ }}
                port:
                  number: {{ $.Values.service.port }}
          {{- end }}
    {{- end }}
{{- end }}
