{{- if and .Values.crawlerRouting.enabled .Values.crawlerRouting.previewResponder.enabled -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dummy-app.fullname" . }}-preview-echo
  labels:
    {{- include "dummy-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: preview-echo
spec:
  replicas: {{ .Values.crawlerRouting.previewResponder.replicaCount }}
  selector:
    matchLabels:
      {{- include "dummy-app.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: preview-echo
  template:
    metadata:
      labels:
        {{- include "dummy-app.labels" . | nindent 8 }}
        app.kubernetes.io/component: preview-echo
    spec:
      containers:
      - name: preview-responder
        image: {{ .Values.crawlerRouting.previewResponder.image }}
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: {{ .Values.crawlerRouting.previewResponder.containerPort }}
          name: http
          protocol: TCP
        resources:
          {{- toYaml .Values.crawlerRouting.previewResponder.resources | nindent 10 }}
        volumeMounts:
        - name: preview-page
          mountPath: /usr/share/nginx/html/index.html
          subPath: index.html
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: preview-page
        configMap:
          name: {{ include "dummy-app.fullname" . }}-preview-page
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.crawlerRouting.targetService.name }}
  labels:
    {{- include "dummy-app.labels" . | nindent 4 }}
    app.kubernetes.io/component: preview-echo
spec:
  type: ClusterIP
  ports:
  - port: {{ .Values.crawlerRouting.targetService.port }}
    targetPort: {{ .Values.crawlerRouting.previewResponder.containerPort }}
    protocol: TCP
    name: http
  selector:
    {{- include "dummy-app.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: preview-echo
{{- end }}
