apiVersion: v2
name: cert-manager
description: Umbrella chart that deploys cert-manager for managing TLS certificates.
type: application
version: 1.0.0
dependencies:
  - name: cert-manager
    version: v1.19.0
    repository: https://charts.jetstack.io
