apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: auth-api-db-url
spec:
  secretStoreRef:
    kind: SecretStore
    name: doppler-auth-api

  target:
    name: auth-api-db-url

  data:
    - secretKey: HELLO_WORLD
      remoteRef:
        key: HELLO_WORLD