apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: backend
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: https://github.com/Martinii89/argocd.git
    path: apps/rllobby
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: rllobby
  syncPolicy:
    automated: 
      prune: true 
      selfHeal: true
    syncOptions:
      - CreateNamespace=true